### ISSUE TITLE
aeroo_docs.conf: No module named uno 

### ISSUE THREAD

**Issue by RaffaeleT** [aeroo/aeroo_docs#16]
I experienced it on a fresh Ubuntu 14.04.3.
The only way I solved has been with:
sudo apt-get install libreoffice-script-provider-python
It should be put before:
sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf

**Comment by trixocom** [comment]
I have same problem, but cant resolv! please help..
I did
sudo apt-get install libreoffice-script-provider-python
But when running
sudo python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/usr/local/lib/python3.6/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element'
I already pip3 install uno, css,etc but no luck.
Please help anyone..
thanks in advance!
hector

**Comment by sraps** [comment]
Please check this:
https://stackoverflow.com/questions/38375068/importerror-cannot-import-name-element

**Comment by QuangPhuocDang** [comment]
I did:
sudo apt-get install libreoffice-script-provider-python
And installed python3-uno:
sudo apt-get install python3-uno

But:
`Traceback (most recent call last):
  File "/study/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/study/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/study/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
ImportError: No module named 'uno'`

Help me please!
