### ISSUE TITLE
ImportError: cannot import name 'Element'

### ISSUE THREAD

**Issue by trixocom** [aeroo/aeroo_docs#26]
Cn not instll aeroo_docs server on odoo11, python3.
Insatlled sucesesfully aeroo_lib, base, uno, unotool, but..
root@odoo11:/opt/aeroo/aeroo_docs# python3 /opt/aeroo/aeroo_docs/aeroo-docs start -c /etc/aeroo-docs.conf
Traceback (most recent call last):
  File "/opt/aeroo/aeroo_docs/aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/opt/aeroo/aeroo_docs/aeroo_docs_fncs.py", line 37, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/opt/aeroo/aeroo_docs/DocumentConverter.py", line 34, in <module>
    import uno
  File "/usr/local/lib/python3.6/site-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: cannot import name 'Element'
root@odoo11:/opt/aeroo/aeroo_docs#

**Comment by sraps** [comment]
Please check this:
https://stackoverflow.com/questions/38375068/importerror-cannot-import-name-element

**Comment by QuangPhuocDang** [comment]
I tried installing python3-uno but it does not work. Help me please!
